# Generated by Django 6.0.7 on 2026-07-13 18:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScalarValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_value", models.DateField()),
                ("datetime_value", models.DateTimeField()),
                ("time_value", models.TimeField()),
                ("decimal_value", models.DecimalField(decimal_places=4, max_digits=12)),
                ("duration_value", models.DurationField()),
                ("boolean_value", models.BooleanField()),
                ("uuid_value", models.UUIDField(default=uuid.uuid4)),
                ("json_value", models.JSONField()),
                ("binary_value", models.BinaryField(null=True)),
            ],
        ),
    ]
