name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: pdm-project/setup-pdm@v4
      - name: Build package
        run: pdm build
      - name: Publish package with Trusted Publishing
        uses: pypa/gh-action-pypi-publish@release/v1
